// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datacube_tile_proto.proto

package org.gbif.mapgl.v1;

public final class DatacubeTileProto {
  private DatacubeTileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DatacubeTileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.gbif.mapgl.v1.DatacubeTile)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated uint32 x = 1 [packed = true];</code>
     *
     * <pre>
     * X and Y arrays to locate the pixel
     * </pre>
     */
    java.util.List<java.lang.Integer> getXList();
    /**
     * <code>repeated uint32 x = 1 [packed = true];</code>
     *
     * <pre>
     * X and Y arrays to locate the pixel
     * </pre>
     */
    int getXCount();
    /**
     * <code>repeated uint32 x = 1 [packed = true];</code>
     *
     * <pre>
     * X and Y arrays to locate the pixel
     * </pre>
     */
    int getX(int index);

    /**
     * <code>repeated uint32 y = 2 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getYList();
    /**
     * <code>repeated uint32 y = 2 [packed = true];</code>
     */
    int getYCount();
    /**
     * <code>repeated uint32 y = 2 [packed = true];</code>
     */
    int getY(int index);

    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    java.util.List<org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel> 
        getChannelList();
    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel getChannel(int index);
    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    int getChannelCount();
  }
  /**
   * Protobuf type {@code org.gbif.mapgl.v1.DatacubeTile}
   *
   * <pre>
   **
   * A basic tile with a set of channels for x,y located pixels.
   * The data channel must the same length as the pixels so that the data matches the pixel - that is, the
   * channel data item at index 0 represents the data for the pixel defined by the pixel indexed at x[0] and y[0].
   * This is a simple tile used only for demonstration purposes.  Changes to make:
   *  i.   Make the pixels relative to the previous (improves compression)
   *  ii.  Support necessary metadata for channels
   *  iii. Review all types and ensure the smallest is used (are uint32 the smallest?)
   *  iv.  ZigZag encode if needed
   * </pre>
   */
  public static final class DatacubeTile extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:org.gbif.mapgl.v1.DatacubeTile)
      DatacubeTileOrBuilder {
    // Use DatacubeTile.newBuilder() to construct.
    private DatacubeTile(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DatacubeTile(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final DatacubeTile defaultInstance;
    public static DatacubeTile getDefaultInstance() {
      return defaultInstance;
    }

    public DatacubeTile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private DatacubeTile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                x_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              x_.add(input.readUInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                x_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                x_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                y_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              y_.add(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                y_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                y_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                channel_ = new java.util.ArrayList<org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel>();
                mutable_bitField0_ |= 0x00000004;
              }
              channel_.add(input.readMessage(org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = java.util.Collections.unmodifiableList(x_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = java.util.Collections.unmodifiableList(y_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          channel_ = java.util.Collections.unmodifiableList(channel_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<DatacubeTile> PARSER =
        new com.google.protobuf.AbstractParser<DatacubeTile>() {
      public DatacubeTile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DatacubeTile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DatacubeTile> getParserForType() {
      return PARSER;
    }

    public interface ChannelOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.gbif.mapgl.v1.DatacubeTile.Channel)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>repeated uint32 value = 1 [packed = true];</code>
       */
      java.util.List<java.lang.Integer> getValueList();
      /**
       * <code>repeated uint32 value = 1 [packed = true];</code>
       */
      int getValueCount();
      /**
       * <code>repeated uint32 value = 1 [packed = true];</code>
       */
      int getValue(int index);
    }
    /**
     * Protobuf type {@code org.gbif.mapgl.v1.DatacubeTile.Channel}
     */
    public static final class Channel extends
        com.google.protobuf.GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.gbif.mapgl.v1.DatacubeTile.Channel)
        ChannelOrBuilder {
      // Use Channel.newBuilder() to construct.
      private Channel(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Channel(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

      private static final Channel defaultInstance;
      public static Channel getDefaultInstance() {
        return defaultInstance;
      }

      public Channel getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.ByteString unknownFields;
      private Channel(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.ByteString.Output unknownFieldsOutput =
            com.google.protobuf.ByteString.newOutput();
        com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
            com.google.protobuf.CodedOutputStream.newInstance(
                unknownFieldsOutput);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  value_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                value_.add(input.readUInt32());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                  value_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                while (input.getBytesUntilLimit() > 0) {
                  value_.add(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = java.util.Collections.unmodifiableList(value_);
          }
          try {
            unknownFieldsCodedOutput.flush();
          } catch (java.io.IOException e) {
          // Should not happen
          } finally {
            unknownFields = unknownFieldsOutput.toByteString();
          }
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<Channel> PARSER =
          new com.google.protobuf.AbstractParser<Channel>() {
        public Channel parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Channel(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Channel> getParserForType() {
        return PARSER;
      }

      public static final int VALUE_FIELD_NUMBER = 1;
      private java.util.List<java.lang.Integer> value_;
      /**
       * <code>repeated uint32 value = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getValueList() {
        return value_;
      }
      /**
       * <code>repeated uint32 value = 1 [packed = true];</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated uint32 value = 1 [packed = true];</code>
       */
      public int getValue(int index) {
        return value_.get(index);
      }
      private int valueMemoizedSerializedSize = -1;

      private void initFields() {
        value_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (getValueList().size() > 0) {
          output.writeRawVarint32(10);
          output.writeRawVarint32(valueMemoizedSerializedSize);
        }
        for (int i = 0; i < value_.size(); i++) {
          output.writeUInt32NoTag(value_.get(i));
        }
        output.writeRawBytes(unknownFields);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < value_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeUInt32SizeNoTag(value_.get(i));
          }
          size += dataSize;
          if (!getValueList().isEmpty()) {
            size += 1;
            size += com.google.protobuf.CodedOutputStream
                .computeInt32SizeNoTag(dataSize);
          }
          valueMemoizedSerializedSize = dataSize;
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code org.gbif.mapgl.v1.DatacubeTile.Channel}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel, Builder>
          implements
          // @@protoc_insertion_point(builder_implements:org.gbif.mapgl.v1.DatacubeTile.Channel)
          org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.ChannelOrBuilder {
        // Construct using org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel getDefaultInstanceForType() {
          return org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel.getDefaultInstance();
        }

        public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel build() {
          org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel buildPartial() {
          org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel result = new org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = java.util.Collections.unmodifiableList(value_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.value_ = value_;
          return result;
        }

        public Builder mergeFrom(org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel other) {
          if (other == org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel.getDefaultInstance()) return this;
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            
          }
          setUnknownFields(
              getUnknownFields().concat(other.unknownFields));
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<java.lang.Integer> value_ = java.util.Collections.emptyList();
        private void ensureValueIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = new java.util.ArrayList<java.lang.Integer>(value_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated uint32 value = 1 [packed = true];</code>
         */
        public java.util.List<java.lang.Integer>
            getValueList() {
          return java.util.Collections.unmodifiableList(value_);
        }
        /**
         * <code>repeated uint32 value = 1 [packed = true];</code>
         */
        public int getValueCount() {
          return value_.size();
        }
        /**
         * <code>repeated uint32 value = 1 [packed = true];</code>
         */
        public int getValue(int index) {
          return value_.get(index);
        }
        /**
         * <code>repeated uint32 value = 1 [packed = true];</code>
         */
        public Builder setValue(
            int index, int value) {
          ensureValueIsMutable();
          value_.set(index, value);
          
          return this;
        }
        /**
         * <code>repeated uint32 value = 1 [packed = true];</code>
         */
        public Builder addValue(int value) {
          ensureValueIsMutable();
          value_.add(value);
          
          return this;
        }
        /**
         * <code>repeated uint32 value = 1 [packed = true];</code>
         */
        public Builder addAllValue(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, value_);
          
          return this;
        }
        /**
         * <code>repeated uint32 value = 1 [packed = true];</code>
         */
        public Builder clearValue() {
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:org.gbif.mapgl.v1.DatacubeTile.Channel)
      }

      static {
        defaultInstance = new Channel(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:org.gbif.mapgl.v1.DatacubeTile.Channel)
    }

    public static final int X_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> x_;
    /**
     * <code>repeated uint32 x = 1 [packed = true];</code>
     *
     * <pre>
     * X and Y arrays to locate the pixel
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getXList() {
      return x_;
    }
    /**
     * <code>repeated uint32 x = 1 [packed = true];</code>
     *
     * <pre>
     * X and Y arrays to locate the pixel
     * </pre>
     */
    public int getXCount() {
      return x_.size();
    }
    /**
     * <code>repeated uint32 x = 1 [packed = true];</code>
     *
     * <pre>
     * X and Y arrays to locate the pixel
     * </pre>
     */
    public int getX(int index) {
      return x_.get(index);
    }
    private int xMemoizedSerializedSize = -1;

    public static final int Y_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> y_;
    /**
     * <code>repeated uint32 y = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getYList() {
      return y_;
    }
    /**
     * <code>repeated uint32 y = 2 [packed = true];</code>
     */
    public int getYCount() {
      return y_.size();
    }
    /**
     * <code>repeated uint32 y = 2 [packed = true];</code>
     */
    public int getY(int index) {
      return y_.get(index);
    }
    private int yMemoizedSerializedSize = -1;

    public static final int CHANNEL_FIELD_NUMBER = 3;
    private java.util.List<org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel> channel_;
    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    public java.util.List<org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel> getChannelList() {
      return channel_;
    }
    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    public java.util.List<? extends org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.ChannelOrBuilder> 
        getChannelOrBuilderList() {
      return channel_;
    }
    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    public int getChannelCount() {
      return channel_.size();
    }
    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel getChannel(int index) {
      return channel_.get(index);
    }
    /**
     * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
     *
     * <pre>
     * each channel is of the same length as x and Y
     * </pre>
     */
    public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.ChannelOrBuilder getChannelOrBuilder(
        int index) {
      return channel_.get(index);
    }

    private void initFields() {
      x_ = java.util.Collections.emptyList();
      y_ = java.util.Collections.emptyList();
      channel_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getXList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(xMemoizedSerializedSize);
      }
      for (int i = 0; i < x_.size(); i++) {
        output.writeUInt32NoTag(x_.get(i));
      }
      if (getYList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(yMemoizedSerializedSize);
      }
      for (int i = 0; i < y_.size(); i++) {
        output.writeUInt32NoTag(y_.get(i));
      }
      for (int i = 0; i < channel_.size(); i++) {
        output.writeMessage(3, channel_.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < x_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(x_.get(i));
        }
        size += dataSize;
        if (!getXList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        xMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < y_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(y_.get(i));
        }
        size += dataSize;
        if (!getYList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        yMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < channel_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, channel_.get(i));
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code org.gbif.mapgl.v1.DatacubeTile}
     *
     * <pre>
     **
     * A basic tile with a set of channels for x,y located pixels.
     * The data channel must the same length as the pixels so that the data matches the pixel - that is, the
     * channel data item at index 0 represents the data for the pixel defined by the pixel indexed at x[0] and y[0].
     * This is a simple tile used only for demonstration purposes.  Changes to make:
     *  i.   Make the pixels relative to the previous (improves compression)
     *  ii.  Support necessary metadata for channels
     *  iii. Review all types and ensure the smallest is used (are uint32 the smallest?)
     *  iv.  ZigZag encode if needed
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:org.gbif.mapgl.v1.DatacubeTile)
        org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTileOrBuilder {
      // Construct using org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile getDefaultInstanceForType() {
        return org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.getDefaultInstance();
      }

      public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile build() {
        org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile buildPartial() {
        org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile result = new org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = java.util.Collections.unmodifiableList(x_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.x_ = x_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = java.util.Collections.unmodifiableList(y_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.y_ = y_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          channel_ = java.util.Collections.unmodifiableList(channel_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.channel_ = channel_;
        return result;
      }

      public Builder mergeFrom(org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile other) {
        if (other == org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.getDefaultInstance()) return this;
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          
        }
        if (!other.y_.isEmpty()) {
          if (y_.isEmpty()) {
            y_ = other.y_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureYIsMutable();
            y_.addAll(other.y_);
          }
          
        }
        if (!other.channel_.isEmpty()) {
          if (channel_.isEmpty()) {
            channel_ = other.channel_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureChannelIsMutable();
            channel_.addAll(other.channel_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> x_ = java.util.Collections.emptyList();
      private void ensureXIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = new java.util.ArrayList<java.lang.Integer>(x_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 x = 1 [packed = true];</code>
       *
       * <pre>
       * X and Y arrays to locate the pixel
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getXList() {
        return java.util.Collections.unmodifiableList(x_);
      }
      /**
       * <code>repeated uint32 x = 1 [packed = true];</code>
       *
       * <pre>
       * X and Y arrays to locate the pixel
       * </pre>
       */
      public int getXCount() {
        return x_.size();
      }
      /**
       * <code>repeated uint32 x = 1 [packed = true];</code>
       *
       * <pre>
       * X and Y arrays to locate the pixel
       * </pre>
       */
      public int getX(int index) {
        return x_.get(index);
      }
      /**
       * <code>repeated uint32 x = 1 [packed = true];</code>
       *
       * <pre>
       * X and Y arrays to locate the pixel
       * </pre>
       */
      public Builder setX(
          int index, int value) {
        ensureXIsMutable();
        x_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated uint32 x = 1 [packed = true];</code>
       *
       * <pre>
       * X and Y arrays to locate the pixel
       * </pre>
       */
      public Builder addX(int value) {
        ensureXIsMutable();
        x_.add(value);
        
        return this;
      }
      /**
       * <code>repeated uint32 x = 1 [packed = true];</code>
       *
       * <pre>
       * X and Y arrays to locate the pixel
       * </pre>
       */
      public Builder addAllX(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, x_);
        
        return this;
      }
      /**
       * <code>repeated uint32 x = 1 [packed = true];</code>
       *
       * <pre>
       * X and Y arrays to locate the pixel
       * </pre>
       */
      public Builder clearX() {
        x_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }

      private java.util.List<java.lang.Integer> y_ = java.util.Collections.emptyList();
      private void ensureYIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = new java.util.ArrayList<java.lang.Integer>(y_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 y = 2 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getYList() {
        return java.util.Collections.unmodifiableList(y_);
      }
      /**
       * <code>repeated uint32 y = 2 [packed = true];</code>
       */
      public int getYCount() {
        return y_.size();
      }
      /**
       * <code>repeated uint32 y = 2 [packed = true];</code>
       */
      public int getY(int index) {
        return y_.get(index);
      }
      /**
       * <code>repeated uint32 y = 2 [packed = true];</code>
       */
      public Builder setY(
          int index, int value) {
        ensureYIsMutable();
        y_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated uint32 y = 2 [packed = true];</code>
       */
      public Builder addY(int value) {
        ensureYIsMutable();
        y_.add(value);
        
        return this;
      }
      /**
       * <code>repeated uint32 y = 2 [packed = true];</code>
       */
      public Builder addAllY(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureYIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, y_);
        
        return this;
      }
      /**
       * <code>repeated uint32 y = 2 [packed = true];</code>
       */
      public Builder clearY() {
        y_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }

      private java.util.List<org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel> channel_ =
        java.util.Collections.emptyList();
      private void ensureChannelIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          channel_ = new java.util.ArrayList<org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel>(channel_);
          bitField0_ |= 0x00000004;
         }
      }

      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public java.util.List<org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel> getChannelList() {
        return java.util.Collections.unmodifiableList(channel_);
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public int getChannelCount() {
        return channel_.size();
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel getChannel(int index) {
        return channel_.get(index);
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder setChannel(
          int index, org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelIsMutable();
        channel_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder setChannel(
          int index, org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel.Builder builderForValue) {
        ensureChannelIsMutable();
        channel_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder addChannel(org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelIsMutable();
        channel_.add(value);

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder addChannel(
          int index, org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelIsMutable();
        channel_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder addChannel(
          org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel.Builder builderForValue) {
        ensureChannelIsMutable();
        channel_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder addChannel(
          int index, org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel.Builder builderForValue) {
        ensureChannelIsMutable();
        channel_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder addAllChannel(
          java.lang.Iterable<? extends org.gbif.mapgl.v1.DatacubeTileProto.DatacubeTile.Channel> values) {
        ensureChannelIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, channel_);

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder clearChannel() {
        channel_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);

        return this;
      }
      /**
       * <code>repeated .org.gbif.mapgl.v1.DatacubeTile.Channel channel = 3;</code>
       *
       * <pre>
       * each channel is of the same length as x and Y
       * </pre>
       */
      public Builder removeChannel(int index) {
        ensureChannelIsMutable();
        channel_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.gbif.mapgl.v1.DatacubeTile)
    }

    static {
      defaultInstance = new DatacubeTile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.gbif.mapgl.v1.DatacubeTile)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
